### 🔁 PyTorch
Tensor Creation
Create a 2D tensor of shape (3, 4) filled with random values.

Print its shape and datatype.


In [14]:
# %pip install torch

In [16]:
import torch

In [22]:
tensor = torch.rand(3,4)
        
print (tensor)
print (tensor.shape)
print (type(tensor))

tensor([[0.2991, 0.1386, 0.0347, 0.4336],
        [0.5118, 0.1207, 0.0092, 0.2391],
        [0.3965, 0.4101, 0.8889, 0.0899]])
torch.Size([3, 4])
<class 'torch.Tensor'>


### Tensor Operations
Perform element-wise addition, subtraction, and matrix multiplication using two tensors of shape (2, 2).

In [27]:
tensor1 = torch.rand(2,2)
tensor2 = torch.rand(2,2)
print (tensor1 + tensor2)
print (tensor1 - tensor2)
print (tensor1 * tensor2)

tensor([[1.3283, 0.6327],
        [0.7917, 1.4076]])
tensor([[ 0.3763, -0.1897],
        [ 0.6718,  0.1656]])
tensor([[0.4057, 0.0911],
        [0.0439, 0.4885]])


### Autograd Basics
Create a tensor with requires_grad=True. Perform a few operations on it and then call .backward() to compute gradients. Print the gradients.


In [41]:
tensor1 = torch.randn(2, 2, requires_grad=True)
tensor2 = tensor1 + 2
tensor3 = tensor2 * tensor2 * 3

print (tensor1)
print (tensor2)
print (tensor3)

out = tensor3.mean()
out.backward()

tensor1.grad

tensor([[-0.6047, -1.7458],
        [ 1.9788,  0.4398]], requires_grad=True)
tensor([[1.3953, 0.2542],
        [3.9788, 2.4398]], grad_fn=<AddBackward0>)
tensor([[ 5.8406,  0.1938],
        [47.4916, 17.8575]], grad_fn=<MulBackward0>)


tensor([[2.0929, 0.3813],
        [5.9681, 3.6597]])

### Linear Layer with nn.Linear
Create a simple nn.Linear layer with input size 4 and output size 2. Pass a dummy tensor through it and print the output.

In [45]:
import torch.nn as nn

linear = nn.Linear(4,2)
dummy_input = torch.rand(1,4)
output = linear(dummy_input)

output

tensor([[0.6549, 0.2250]], grad_fn=<AddmmBackward0>)

### Build a Tiny Neural Network
Use nn.Sequential to build a neural network with:

Input layer: 3 neurons

Hidden layer: 5 neurons with ReLU

Output layer: 1 neuron with Sigmoid
Pass a dummy input tensor of shape (1, 3) through the model.

In [49]:
model = nn.Sequential(
    nn.Linear(3,5),
    nn.ReLU(),
    nn.Linear(5,1),
    nn.Sigmoid()
)

dummy_input = torch.rand(1,3)
output = model(dummy_input)

In [53]:
print("Dummy Input:\n", dummy_input)
print("Model Output:\n", output)

Dummy Input:
 tensor([[0.1740, 0.1836, 0.1522]])
Model Output:
 tensor([[0.4272]], grad_fn=<SigmoidBackward0>)
